version: "3"
services:
  receiver:
    build:
      context: .
      args:
        GIT_USER: your_git_username
        GIT_EMAIL: your@email.com
    container_name: foam_receiver
    volumes:
      - /home/your_username/.ssh/:/root/.ssh/
      - ./.env/:/app/.env
    ports:
      - '127.0.0.1:3000:3000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.receiver.entrypoints=http"
      - "traefik.http.routers.receiver.tls=true"
      - "traefik.http.routers.receiver.tls.certresolver=myresolver"
      - "traefik.http.routers.receiver.rule=Host(`foam-receiver.example.com`)"